name: Generate Bash Script

on:
  workflow_dispatch:
  push:
    branches:
      - main
  repository_dispatch:
    types: [file-changed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy ubuntu-jammy-upgrade-script.sh
        run: |
          curl -sS https://raw.githubusercontent.com/brettjrea/GitHub_Generate_Readme/main/bash/ubuntu-jammy-upgrade-script.sh --output debian-bullseye-upgrade-script.sh
      

      - name: Auto commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Auto commit copied ubuntu-jammy-upgrade-script.sh'
